let flagDict = {
  AED: "ae",
  AFN: "af",
  XCD: "ag",
  ALL: "al",
  AMD: "am",
  ANG: "ao",
  AOA: "ao",
  AQD: "aq",
  ARS: "ar",
  AUD: "au",
  AZN: "az",
  BAM: "ba",
  BBD: "bb",
  BDT: "bd",
  XOF: "be",
  BGN: "bg",
  BHD: "bh",
  BIF: "bi",
  BMD: "bm",
  BND: "bn",
  BOB: "bo",
  BRL: "br",
  BSD: "bs",
  NOK: "bv",
  BWP: "bw",
  BYR: "by",
  BZD: "bz",
  CAD: "ca",
  CDF: "cd",
  XAF: "cf",
  CHF: "ch",
  CLP: "cl",
  CNY: "cn",
  COP: "co",
  CRC: "cr",
  CUP: "cu",
  CVE: "cv",
  CYP: "cy",
  CZK: "cz",
  DJF: "dj",
  DKK: "dk",
  DOP: "do",
  DZD: "dz",
  ECS: "ec",
  EEK: "ee",
  EGP: "eg",
  ETB: "et",
  EUR: "fr",
  FJD: "fj",
  FKP: "fk",
  GBP: "gb",
  GEL: "ge",
  GGP: "gg",
  GHS: "gh",
  GIP: "gi",
  GMD: "gm",
  GNF: "gn",
  GTQ: "gt",
  GYD: "gy",
  HKD: "hk",
  HNL: "hn",
  HRK: "hr",
  HTG: "ht",
  HUF: "hu",
  IDR: "id",
  ILS: "il",
  INR: "in",
  IQD: "iq",
  IRR: "ir",
  ISK: "is",
  JMD: "jm",
  JOD: "jo",
  JPY: "jp",
  KES: "ke",
  KGS: "kg",
  KHR: "kh",
  KMF: "km",
  KPW: "kp",
  KRW: "kr",
  KWD: "kw",
  KYD: "ky",
  KZT: "kz",
  LAK: "la",
  LBP: "lb",
  LKR: "lk",
  LRD: "lr",
  LSL: "ls",
  LTL: "lt",
  LVL: "lv",
  LYD: "ly",
  MAD: "ma",
  MDL: "md",
  MGA: "mg",
  MKD: "mk",
  MMK: "mm",
  MNT: "mn",
  MOP: "mo",
  MRO: "mr",
  MTL: "mt",
  MUR: "mu",
  MVR: "mv",
  MWK: "mw",
  MXN: "mx",
  MYR: "my",
  MZN: "mz",
  NAD: "na",
  XPF: "nc",
  NGN: "ng",
  NIO: "ni",
  NPR: "np",
  NZD: "nz",
  OMR: "om",
  PAB: "pa",
  PEN: "pe",
  PGK: "pg",
  PHP: "ph",
  PKR: "pk",
  PLN: "pl",
  PYG: "py",
  QAR: "qa",
  RON: "ro",
  RSD: "rs",
  RUB: "ru",
  RWF: "rw",
  SAR: "sa",
  SBD: "sb",
  SCR: "sc",
  SDG: "sd",
  SEK: "se",
  SGD: "sg",
  SKK: "sk",
  SLL: "sl",
  SOS: "so",
  SRD: "sr",
  STD: "st",
  SVC: "sv",
  SYP: "sy",
  SZL: "sz",
  THB: "th",
  TJS: "tj",
  TMT: "tm",
  TND: "tn",
  TOP: "to",
  TRY: "tr",
  TTD: "tt",
  TWD: "tw",
  TZS: "tz",
  UAH: "ua",
  UGX: "ug",
  USD: "us",
  UYU: "uy",
  UZS: "uz",
  VEF: "ve",
  VND: "vn",
  VUV: "vu",
  YER: "ye",
  ZAR: "za",
  ZMK: "zm",
  ZWD: "zw",
};


let currencyDict = {
  AED: "AED - United Arab Emirates Dirham",
  AFN: "AFN - Afghan Afghani",
  XCD: "XCD - East Caribbean Dollar",
  ALL: "ALL - Albanian Lek",
  AMD: "AMD - Armenian Dram",
  ANG: "ANG - Netherlands Antillean Guilder",
  AOA: "AOA - Angolan Kwanza",
  AQD: "AQD - Antarctican Dollar",
  ARS: "ARS - Argentine Peso",
  AUD: "AUD - Australian Dollar",
  AZN: "AZN - Azerbaijani Manat",
  BAM: "BAM - Bosnia-Herzegovina Convertible Mark",
  BBD: "BBD - Barbadian Dollar",
  BDT: "BDT - Bangladeshi Taka",
  XOF: "XOF - West African CFA Franc",
  BGN: "BGN - Bulgarian Lev",
  BHD: "BHD - Bahraini Dinar",
  BIF: "BIF - Burundian Franc",
  BMD: "BMD - Bermudan Dollar",
  BND: "BND - Brunei Dollar",
  BOB: "BOB - Bolivian Boliviano",
  BRL: "BRL - Brazilian Real",
  BSD: "BSD - Bahamian Dollar",
  NOK: "NOK - Norwegian Krone",
  BWP: "BWP - Botswanan Pula",
  BYR: "BYR - Belarusian Ruble",
  BZD: "BZD - Belize Dollar",
  CAD: "CAD - Canadian Dollar",
  CDF: "CDF - Congolese Franc",
  XAF: "XAF - Central African CFA Franc",
  CHF: "CHF - Swiss Franc",
  CLP: "CLP - Chilean Peso",
  CNY: "CNY - Chinese Yuan",
  COP: "COP - Colombian Peso",
  CRC: "CRC - Costa Rican Colón",
  CUP: "CUP - Cuban Peso",
  CVE: "CVE - Cape Verdean Escudo",
  CYP: "CYP - Cypriot Pound",
  CZK: "CZK - Czech Koruna",
  DJF: "DJF - Djiboutian Franc",
  DKK: "DKK - Danish Krone",
  DOP: "DOP - Dominican Peso",
  DZD: "DZD - Algerian Dinar",
  ECS: "ECS - Ecuadorian Sucre",
  EEK: "EEK - Estonian Kroon",
  EGP: "EGP - Egyptian Pound",
  ETB: "ETB - Ethiopian Birr",
  EUR: "EUR - Euro",
  FJD: "FJD - Fijian Dollar",
  FKP: "FKP - Falkland Islands Pound",
  GBP: "GBP - British Pound Sterling",
  GEL: "GEL - Georgian Lari",
  GGP: "GGP - Guernsey Pound",
  GHS: "GHS - Ghanaian Cedi",
  GIP: "GIP - Gibraltar Pound",
  GMD: "GMD - Gambian Dalasi",
  GNF: "GNF - Guinean Franc",
  GTQ: "GTQ - Guatemalan Quetzal",
  GYD: "GYD - Guyanaese Dollar",
  HKD: "HKD - Hong Kong Dollar",
  HNL: "HNL - Honduran Lempira",
  HRK: "HRK - Croatian Kuna",
  HTG: "HTG - Haitian Gourde",
  HUF: "HUF - Hungarian Forint",
  IDR: "IDR - Indonesian Rupiah",
  ILS: "ILS - Israeli New Shekel",
  INR: "INR - Indian Rupee",
  IQD: "IQD - Iraqi Dinar",
  IRR: "IRR - Iranian Rial",
  ISK: "ISK - Icelandic Króna",
  JMD: "JMD - Jamaican Dollar",
  JOD: "JOD - Jordanian Dinar",
  JPY: "JPY - Japanese Yen",
  KES: "KES - Kenyan Shilling",
  KGS: "KGS - Kyrgystani Som",
  KHR: "KHR - Cambodian Riel",
  KMF: "KMF - Comorian Franc",
  KPW: "KPW - North Korean Won",
  KRW: "KRW - South Korean Won",
  KWD: "KWD - Kuwaiti Dinar",
  KYD: "KYD - Cayman Islands Dollar",
  KZT: "KZT - Kazakhstani Tenge",
  LAK: "LAK - Laotian Kip",
  LBP: "LBP - Lebanese Pound",
  LKR: "LKR - Sri Lankan Rupee",
  LRD: "LRD - Liberian Dollar",
  LSL: "LSL - Lesotho Loti",
  LTL: "LTL - Lithuanian Litas",
  LVL: "LVL - Latvian Lats",
  LYD: "LYD - Libyan Dinar",
  MAD: "MAD - Moroccan Dirham",
  MDL: "MDL - Moldovan Leu",
  MGA: "MGA - Malagasy Ariary",
  MKD: "MKD - Macedonian Denar",
  MMK: "MMK - Myanmar Kyat",
  MNT: "MNT - Mongolian Tugrik",
  MOP: "MOP - Macanese Pataca",
  MRO: "MRO - Mauritanian Ouguiya",
  MTL: "MTL - Maltese Lira",
  MUR: "MUR - Mauritian Rupee",
  MVR: "MVR - Maldivian Rufiyaa",
  MWK: "MWK - Malawian Kwacha",
  MXN: "MXN - Mexican Peso",
  MYR: "MYR - Malaysian Ringgit",
  MZN: "MZN - Mozambican Metical",
  NAD: "NAD - Namibian Dollar",
  XPF: "XPF - CFP Franc",
  NGN: "NGN - Nigerian Naira",
  NIO: "NIO - Nicaraguan Córdoba",
  NPR: "NPR - Nepalese Rupee",
  NZD: "NZD - New Zealand Dollar",
  OMR: "OMR - Omani Rial",
  PAB: "PAB - Panamanian Balboa",
  PEN: "PEN - Peruvian Sol",
  PGK: "PGK - Papua New Guinean Kina",
  PHP: "PHP - Philippine Peso",
  PKR: "PKR - Pakistani Rupee",
  PLN: "PLN - Polish Złoty",
  PYG: "PYG - Paraguayan Guaraní",
  QAR: "QAR - Qatari Riyal",
  RON: "RON - Romanian Leu",
  RSD: "RSD - Serbian Dinar",
  RUB: "RUB - Russian Ruble",
  RWF: "RWF - Rwandan Franc",
  SAR: "SAR - Saudi Riyal",
  SBD: "SBD - Solomon Islands Dollar",
  SCR: "SCR - Seychellois Rupee",
  SDG: "SDG - Sudanese Pound",
  SEK: "SEK - Swedish Krona",
  SGD: "SGD - Singapore Dollar",
  SKK: "SKK - Slovak Koruna",
  SLL: "SLL - Sierra Leonean Leone",
  SOS: "SOS - Somali Shilling",
  SRD: "SRD - Surinamese Dollar",
  STD: "STD - São Tomé and Príncipe Dobra",
  SVC: "SVC - Salvadoran Colón",
  SYP: "SYP - Syrian Pound",
  SZL: "SZL - Swazi Lilangeni",
  THB: "THB - Thai Baht",
  TJS: "TJS - Tajikistani Somoni",
  TMT: "TMT - Turkmenistani Manat",
  TND: "TND - Tunisian Dinar",
  TOP: "TOP - Tongan Paʻanga",
  TRY: "TRY - Turkish Lira",
  TTD: "TTD - Trinidad and Tobago Dollar",
  TWD: "TWD - New Taiwan Dollar",
  TZS: "TZS - Tanzanian Shilling",
  UAH: "UAH - Ukrainian Hryvnia",
  UGX: "UGX - Ugandan Shilling",
  USD: "USD - United States Dollar",
  UYU: "UYU - Uruguayan Peso",
  UZS: "UZS - Uzbekistani Som",
  VEF: "VEF - Venezuelan Bolívar",
  VND: "VND - Vietnamese Đồng",
  VUV: "VUV - Vanuatu Vatu",
  YER: "YER - Yemeni Rial",
  ZAR: "ZAR - South African Rand",
  ZMK: "ZMK - Zambian Kwacha",
  ZWD: "ZWD - Zimbabwean Dollar",
};